# Dependencies
# markdown:         redcarpet
rouge:      true

# Permalinks
permalink:        pretty

# Setup
title:            Centrally Distributed
tagline:          'from c++ to fixed-income markets, and everything in between'
description:      'a personal blog'
url:              http://estinox.github.io
baseurl:          ''
gems:             [jekyll-paginate]
paginate:         5
excerpt_separator: <!--more-->

github:
  repo:           https://github.com/estinox

# Contacts
author:
  name:           'Kevin Yuan'
  url:            http://estinox.github.io
  email:          kevinyuan558 (little mice sign) gmail dot com
