# Dependencies
# markdown:         redcarpet
rouge:      true

# Permalinks
permalink:        pretty

# Setup
title:            Centrally Distributed
tagline:          'from statistics to photography, and everything in-between'
description:      'Centrally Distributed'
url:              http://estinox.github.io

author:
  name:           'Kevin Yuan'
  url:            http://estinox.github.io 

gems: [jekyll-paginate]
paginate:         5
excerpt_separator: <!--more-->

# Custom vars
version:          1.0

github:
  repo:           https://github.com/estinox
